### ISSUE TITLE
latest update graphs 2.3.0 ruined common annotations json & hive in build_runner

### ISSUE THREAD

**Issue by forsytalnd** [dart-lang/graphs#86]
I dunno if this is your issue, but...
Your library is in dependencies in `build_runner` and after last updating 2.2.0 --> 2.3.0 an issue was happened.

When there are both annotations in class, like that, 

```dart

part 'user.freezed.dart';
part 'user.g.dart';

/// Класс пользователя для авторизации
@freezed
class AuthUser with _$AuthUser {
  /// Базовый класс typeId: 0, adapterName: 'AuthUserAdapter'
  @HiveType(typeId: 0)
  const factory AuthUser({
    @HiveField(0) required String id,
  }) = _AuthUser;

  /// AuthUser.fromJson
  factory AuthUser.fromJson(Map<String, dynamic> json) =>
      _$AuthUserFromJson(json);

```

`json_annotation` which is indirectly called from `freezed` had been adding its annotations in ".g.dart" alongside with `hive`

```dart
part of 'user.dart';

// **************************************************************************
// TypeAdapterGenerator
// **************************************************************************

class AuthUserAdapter extends TypeAdapter<_$_AuthUser> {
  @override
  final int typeId = 0;


// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

_$_AuthUser _$$_AuthUserFromJson(Map<String, dynamic> json) => $checkedCreate(
      r'_$_AuthUser',
      json,
      ($checkedConvert) {
        final val = _$_AuthUser(

```

As a result of last night updating of `graphs` json generator overrides file `.g.dart` and previous info disappears.

I added this issue to build_runner repository too.

**Comment by spioc999** [comment]
I had a similar issue.
As also mentioned in this [thread](https://github.com/petercinibulk/envied/issues/28), the issue was solved adding these lines in `pubspec.yaml`

`
dependency_overrides: 
  graphs: 2.2.0 
`

But, please, fix it!

**Comment by jakemac53** [comment]
cc @nex3 I wonder if the changes to `topologicalSort` and `stronglyConnectedComponents` broke this somehow, looking into it though.

**Comment by jakemac53** [comment]
I do see a difference in builder ordering here - specifically `hive_generator` now appears before `freezed`.

These packages presumably don't depend on each other and so the order is undefined technically - either is a valid topological sort.

However it appears that `hive_generator` does rely on running second today? And it isn't giving any sort of error which it probably should be.

**Comment by jakemac53** [comment]
cc @natebosch

**Comment by jakemac53** [comment]
Adding this configuration to your `build.yaml` should fix the issue:

```yaml
global_options:
  freezed:
    runs_before:
      - hive_generator
```

**Comment by jakemac53** [comment]
I am not sure if it is worth trying to revert the ordering behavior of this package back to what it was previously or not. It is explicitly not defined, and builder ordering is similarly explicitly not defined if there is no explicit configuration via `runs_before`.

**Comment by jakemac53** [comment]
We could also do a separate ordering pass in build_runner potentially.

**Comment by jakemac53** [comment]
Also cc @rrousselGit technically I think freezed could add this configuration directly, although its a bit weird for you to do so, I believe it is allowed to be there even if a project doesn't depend on hive_generator. A bit of a slippery slope potentially though.

**Comment by muhammadkamel** [comment]
> 

This worked for me
Thank you :)

**Comment by gaetschwartz** [comment]
@jakemac53 in my case, I already had an ordering defined using runs_before, which used to work before but doesn't with the latest graph update:

```yaml
targets:
  $default:
    auto_apply_builders: false
    builders:
      drift_dev:not_shared:
        enabled: true
        # If needed, you can configure the builder like this:
        options:
          sql:
            dialect: sqlite
            options:
              modules:
                - json1
      riverpod_generator:riverpod_generator:
        enabled: true
      freezed:freezed:
        enabled: true
        generate_for:
          - lib/**/*.gen.dart
          - "lib/generatedDb/models/**"
      json_serializable:
        enabled: true
        options:
          # https://pub.dev/packages/json_serializable#build-configuration
          explicit_to_json: true
          checked: true
          field_rename: snake

global_options:
  drift_dev:drift_dev:
    runs_before:
      - riverpod_generator:riverpod_generator
  freezed:freezed:
    runs_before:
      - drift_dev:drift_dev
```

**Comment by rrousselGit** [comment]
> 

Yeah I don't want to do this.  It'd get weird very quickly



But I wonder if this bug is related to https://github.com/dart-lang/build/issues/3503, which is a much more problematic issue I hit recently.
I could see a world where source_gen's `combining_builder` starts to run before the "parts" have been generated in the `.dart_tool` folder.  
Although that's just a wild guess

**Comment by gaetschwartz** [comment]
Here it is, it now doesn't respect the first rule saying drift_dev should be ran before riverpod_generator.

```yaml
targets:
  $default:
    auto_apply_builders: false
    builders:
      drift_dev:not_shared:
        enabled: true
        generate_for:
          - lib/**/drift.dart
          - lib/**/*.drift.dart
          - lib/**/*.drift
        # If needed, you can configure the builder like this:
        options:
          sql:
            dialect: sqlite
            options:
              modules:
                - json1
      riverpod_generator:riverpod_generator:
        enabled: true
      freezed:freezed:
        enabled: true
        generate_for:
          - lib/**/*.gen.dart
      json_serializable:
        generate_for:
          - lib/**/*.gen.dart
        enabled: true
        options:
          # https://pub.dev/packages/json_serializable#build-configuration
          explicit_to_json: true
          checked: true
          field_rename: snake

global_options:
  drift_dev:drift_dev:
    runs_before:
      - riverpod_generator:riverpod_generator
  freezed:freezed:
    runs_before:
      - drift_dev:drift_dev
```

**Comment by jakemac53** [comment]
@gaetschwartz When I look at the generated build file I do see `drift_dev:drift_dev` coming before `riverpod_generator:riverpod_generator`.  But there are several other `drift_dev` related builders, and I am guessing that some or all of them also need to come before `riverpod_generator`.

In particular, here is my builder applications list:

```dart
final _builders = <_i1.BuilderApplication>[
  _i1.apply(
    r'drift_dev:preparing_builder',
    [_i2.preparingBuilder],
    _i1.toNoneByDefault(),
    hideOutput: true,
    appliesBuilders: const [r'drift_dev:cleanup'],
  ),
  _i1.apply(
    r'freezed:freezed',
    [_i3.freezed],
    _i1.toDependentsOf(r'freezed'),
    hideOutput: false,
  ),
  _i1.apply(
    r'drift_dev:drift_dev',
    [
      _i2.analyzer,
      _i2.driftBuilder,
    ],
    _i1.toDependentsOf(r'drift_dev'),
    hideOutput: true,
    appliesBuilders: const [
      r'source_gen:combining_builder',
      r'drift_dev:preparing_builder',
    ],
  ),
  _i1.apply(
    r'riverpod_generator:riverpod_generator',
    [_i4.riverpodBuilder],
    _i1.toDependentsOf(r'riverpod_generator'),
    hideOutput: true,
    appliesBuilders: const [r'source_gen:combining_builder'],
  ),
  _i1.apply(
    r'source_gen:combining_builder',
    [_i5.combiningBuilder],
    _i1.toNoneByDefault(),
    hideOutput: false,
    appliesBuilders: const [r'source_gen:part_cleanup'],
  ),
  _i1.apply(
    r'drift_dev:not_shared',
    [_i2.driftBuilderNotShared],
    _i1.toNoneByDefault(),
    hideOutput: false,
  ),
  _i1.apply(
    r'drift_dev:analyzer',
    [_i2.analyzer],
    _i1.toNoneByDefault(),
    hideOutput: true,
    appliesBuilders: const [r'drift_dev:preparing_builder'],
  ),
  _i1.apply(
    r'drift_dev:modular',
    [_i2.modular],
    _i1.toNoneByDefault(),
    hideOutput: false,
    appliesBuilders: const [r'drift_dev:analyzer'],
  ),
  _i1.applyPostProcess(
    r'source_gen:part_cleanup',
    _i5.partCleanup,
  ),
  _i1.applyPostProcess(
    r'drift_dev:cleanup',
    _i2.driftCleanup,
  ),
];
```

cc @simolus3 who I think authors drift_dev and may be able to provide more context.

**Comment by simolus3** [comment]
@gaetschwartz You might just have been lucky about this working before: You are configuring `drift_dev:not_shared` (which is not the same as `drift_dev:drift_dev` - it needs to use a different name because it configures outputs differently and doesn't apply `source_gen:combining_builder`). So your ordering constraints were never really applied to drift.

So your global options should probably look like this:

```yaml
global_options:
  drift_dev:not_shared:
    runs_before:
      - riverpod_generator:riverpod_generator
  freezed:freezed:
    runs_before:
      - drift_dev:not_shared
```

If that doesn't fix it I need to take a deeper look at the build config as well ;D
